// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/coralogix/coralogix-operator/controllers/clientset (interfaces: AlertsClientInterface)
//
// Generated by this command:
//
//	mockgen -destination=../mock_clientset/mock_alerts-client.go -package=mock_clientset github.com/coralogix/coralogix-operator/controllers/clientset AlertsClientInterface
//
// Package mock_clientset is a generated GoMock package.
package mock_clientset

import (
	context "context"
	reflect "reflect"

	__ "github.com/coralogix/coralogix-operator/controllers/clientset/grpc/alerts/v2"
	gomock "go.uber.org/mock/gomock"
)

// MockAlertsClientInterface is a mock of AlertsClientInterface interface.
type MockAlertsClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAlertsClientInterfaceMockRecorder
}

// MockAlertsClientInterfaceMockRecorder is the mock recorder for MockAlertsClientInterface.
type MockAlertsClientInterfaceMockRecorder struct {
	mock *MockAlertsClientInterface
}

// NewMockAlertsClientInterface creates a new mock instance.
func NewMockAlertsClientInterface(ctrl *gomock.Controller) *MockAlertsClientInterface {
	mock := &MockAlertsClientInterface{ctrl: ctrl}
	mock.recorder = &MockAlertsClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAlertsClientInterface) EXPECT() *MockAlertsClientInterfaceMockRecorder {
	return m.recorder
}

// CreateAlert mocks base method.
func (m *MockAlertsClientInterface) CreateAlert(arg0 context.Context, arg1 *__.CreateAlertRequest) (*__.CreateAlertResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAlert", arg0, arg1)
	ret0, _ := ret[0].(*__.CreateAlertResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAlert indicates an expected call of CreateAlert.
func (mr *MockAlertsClientInterfaceMockRecorder) CreateAlert(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAlert", reflect.TypeOf((*MockAlertsClientInterface)(nil).CreateAlert), arg0, arg1)
}

// DeleteAlert mocks base method.
func (m *MockAlertsClientInterface) DeleteAlert(arg0 context.Context, arg1 *__.DeleteAlertByUniqueIdRequest) (*__.DeleteAlertByUniqueIdResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAlert", arg0, arg1)
	ret0, _ := ret[0].(*__.DeleteAlertByUniqueIdResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAlert indicates an expected call of DeleteAlert.
func (mr *MockAlertsClientInterfaceMockRecorder) DeleteAlert(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAlert", reflect.TypeOf((*MockAlertsClientInterface)(nil).DeleteAlert), arg0, arg1)
}

// GetAlert mocks base method.
func (m *MockAlertsClientInterface) GetAlert(arg0 context.Context, arg1 *__.GetAlertByUniqueIdRequest) (*__.GetAlertByUniqueIdResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAlert", arg0, arg1)
	ret0, _ := ret[0].(*__.GetAlertByUniqueIdResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAlert indicates an expected call of GetAlert.
func (mr *MockAlertsClientInterfaceMockRecorder) GetAlert(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAlert", reflect.TypeOf((*MockAlertsClientInterface)(nil).GetAlert), arg0, arg1)
}

// UpdateAlert mocks base method.
func (m *MockAlertsClientInterface) UpdateAlert(arg0 context.Context, arg1 *__.UpdateAlertByUniqueIdRequest) (*__.UpdateAlertByUniqueIdResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAlert", arg0, arg1)
	ret0, _ := ret[0].(*__.UpdateAlertByUniqueIdResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAlert indicates an expected call of UpdateAlert.
func (mr *MockAlertsClientInterfaceMockRecorder) UpdateAlert(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAlert", reflect.TypeOf((*MockAlertsClientInterface)(nil).UpdateAlert), arg0, arg1)
}
