---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coralogix.com
  resources:
  - alerts
  - alertschedulers
  - apikeys
  - customroles
  - dashboards
  - dashboardsfolders
  - groups
  - integrations
  - outboundwebhooks
  - recordingrulegroupsets
  - rulegroups
  - scopes
  - tcologspolicies
  - tcotracespolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coralogix.com
  resources:
  - alerts/finalizers
  - alertschedulers/finalizers
  - apikeys/finalizers
  - customroles/finalizers
  - dashboards/finalizers
  - dashboardsfolders/finalizers
  - groups/finalizers
  - integrations/finalizers
  - outboundwebhooks/finalizers
  - recordingrulegroupsets/finalizers
  - rulegroups/finalizers
  - scopes/finalizers
  - tcologspolicies/finalizers
  - tcotracespolicies/finalizers
  verbs:
  - update
- apiGroups:
  - coralogix.com
  resources:
  - alerts/status
  - alertschedulers/status
  - apikeys/status
  - customroles/status
  - dashboards/status
  - dashboardsfolders/status
  - groups/status
  - integrations/status
  - outboundwebhooks/status
  - recordingrulegroupsets/status
  - rulegroups/status
  - scopes/status
  - tcologspolicies/status
  - tcotracespolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheusrules
  verbs:
  - get
  - list
  - watch
