---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coralogix.com
  resources:
  - alerts
  - recordingrulegroupsets
  - rulegroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coralogix.com
  resources:
  - alerts/finalizers
  - recordingrulegroupsets/finalizers
  - rulegroups/finalizers
  verbs:
  - update
- apiGroups:
  - coralogix.com
  resources:
  - alerts/status
  - recordingrulegroupsets/status
  - rulegroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheusrules
  verbs:
  - get
  - list
  - watch
